version: "3.8"
services:
  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env-docker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7
    env_file:
      - .env-docker
  app:
    build:
      context: .
    env_file:
      - .env-docker
    command: ["/webtronics/docker/start_app.sh"]
    ports:
      - "7999:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

